networks:
  graylog:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  mongodb:
    image: "mongo:5.0"
    container_name: mongodb
    hostname: mongodb1
    restart: always
    command: ["mongod", "--bind_ip_all", "--replSet", "rs0", "--keyFile", "/etc/mongodb/keys/keyfile"]
    ports:
      - "27017:27017/tcp"
    volumes:
      - "mongodb-data:/data/db"
      - "./mongodb/initdb.d:/docker-entrypoint-initdb.d"
      - "./mongodb/init-replset.js:/init-replset.js"
      - "./mongodb/keyfile:/etc/mongodb/keys/keyfile"
    networks:
      graylog:
        ipv4_address: 172.20.0.2

volumes:
  mongodb-data: