version: "3.7"

services:
  ollama-webui:
    image: ${IMAGE_PREFIX}ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ./ollama-webui:/app/backend/data
    ports:
      - 8080:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://host.docker.internal:11344 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=valiantlynx AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped