networks:
  graylog:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  mongodb2:
    image: "mongo:5.0"
    hostname: "mongodb2"
    command: ["mongod", "--bind_ip_all", "--replSet", "rs0"]
    volumes:
      - "mongodb-data-02:/data/db"
    networks:
      graylog:
        ipv4_address: 172.20.0.3
    restart: "on-failure"

volumes:
  mongodb-data-02: