version: "3.5"

services:
  grafana:
    image: ${IMAGE_PREFIX}/grafana/grafana
    container_name: grafana
    host_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./provisioning:/etc/grafana/provisioning:ro
