version: "3.5"
services:
  zabbix-web:
    image: "${REPO_NAME}/${PROJECT}/zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest"
    container_name: zabbix-web
    hostname: zabbix-web
    restart: always
    attach: false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # depends_on:
    #   # - postgres-server
    #   - zabbix-server
    tmpfs: /tmp
    deploy:
      resources:
        # limits:
        #   cpus: '0.70'
        #   memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
    env_file:
      - ./env_vars/.env_web
      - ./env_vars/.env_db_pgsql
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      frontend:
      backend:
        aliases:
          - zabbix-web
      database:
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535
    labels:
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-frontend"
      com.zabbix.description: "Zabbix frontend on Nginx web-server with PostgreSQL database support"
      com.zabbix.webserver: "nginx"
      com.zabbix.dbtype: "pgsql"
      com.zabbix.os: "alpine"

  zabbix-server:
    image: "${REPO_NAME}/${PROJECT}/zabbix/zabbix-server-pgsql:alpine-7.0-latest"
    container_name: zabbix-server
    hostname: zabbix-server
    init: true
    ports:
      - "10051:10051"
    restart: always
    attach: false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
      - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      # - snmptraps:/var/lib/zabbix/snmptraps:roz
      #  - ./zbx_env/tmp/rpm:/var/tmp/rpm:rw
      #  - ./zbx_env/tmp/pip:/var/tmp/pip:rw
    tmpfs: /tmp
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        # limits:
        #   cpus: "0.70"
        #   memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
    env_file:
      - ./env_vars/.env_srv
      - ./env_vars/.env_db_pgsql
    environment:
      - ZBX_HANODENAME=zabbix-server-01
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      database:
        aliases:
          - zabbix-server
      backend:
        aliases:
          - zabbix-server
      frontend:
        aliases:
          - zabbix-server
        ipv4_address: 172.16.238.100
      tools_frontend:
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 64999
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    labels:
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-server"
      com.zabbix.description: "Zabbix server with PostgreSQL database support"
      com.zabbix.dbtype: "pgsql"
      com.zabbix.os: "alpine"

  zabbix-proxy:
    image: "${REPO_NAME}/${PROJECT}/zabbix/zabbix-proxy-mysql:alpine-7.0-latest"
    container_name: zabbix-proxy
    hostname: zabbix-proxy
    init: true
    ports:
      - "10071:10051"
    profiles:
      - all
    restart: always
    attach: false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      # - snmptraps:/var/lib/zabbix/snmptraps:ro
    depends_on:
      - mysql-server
    tmpfs: /tmp
    ulimits:
      nproc: 65535
      nofile:
        # soft: 20000
        # hard: 40000
        soft: 65535
        hard: 65535
    deploy:
      resources:
        # limits:
        #   cpus: '0.70'
        #   memory: 512M
        reservations:
          cpus: "0.3"
          memory: 256M
    env_file:
      - ./env_vars/.env_prx
      - ./env_vars/.env_prx_mysql
      - ./env_vars/.env_db_mysql_proxy
    environment:
      - ZBX_SERVER_HOST=zabbix-server;${XDESK_NODE_02_IP}
      - ZBX_HOSTNAME=zabbix-proxy-01
    secrets:
      - MYSQL_ROOT_USER
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      database:
        aliases:
          - zabbix-proxy
      backend:
        aliases:
          - zabbix-proxy
      frontend:
      tools_frontend:
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 64999
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
      # - net.ipv4.ping_group_range=0 1995
    labels:
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-proxy"
      com.zabbix.description: "Zabbix proxy with MySQL database support"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "alpine"

  mysql-server:
    image: "${REPO_NAME}/${PROJECT}/mysql:8.0-oracle"
    container_name: mysql-server
    hostname: mysql-server
    profiles:
      - all
    command:
      - mysqld
      - --skip-mysqlx
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --skip-log-bin
      # Only during upgrade from versions prior 6.4 and new installations (schema deployment)
      - --log_bin_trust_function_creators=1
    # Use TLS encryption for connections to database
    #   - --require-secure-transport
    #   - --ssl-ca=/run/secrets/root-ca.pem
    #   - --ssl-cert=/run/secrets/server-cert.pem
    #   - --ssl-key=/run/secrets/server-key.pem
    restart: always
    attach: false
    volumes:
      - /data/var/lib/mysql:/var/lib/mysql:rw
      - ./zbx_env/mysql_init/init_proxy_db.sql:/docker-entrypoint-initdb.d/mysql_init_proxy.sql:ro
    #   - dbsocket:/var/run/mysqld/
    env_file:
      - ./env_vars/.env_db_mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    stop_grace_period: 1m
    networks:
      database:
        aliases:
          - mysql-server
networks:
  frontend:
    driver: bridge
    name: frontend
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
  backend:
    driver: bridge
    name: backend
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
  database:
    driver: bridge
    name: database
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
  tools_frontend:
    driver: bridge
    name: tools_frontend
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.240.0/24

volumes:
  snmptraps:

secrets:
  MYSQL_USER:
    file: ./env_vars/.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./env_vars/.MYSQL_PASSWORD
  MYSQL_ROOT_USER:
    file: ./env_vars/.MYSQL_ROOT_USER
  MYSQL_ROOT_PASSWORD:
    file: ./env_vars/.MYSQL_ROOT_PASSWORD
  POSTGRES_USER:
    file: ./env_vars/.POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./env_vars/.POSTGRES_PASSWORD
