version: '3'

services:
  nginx:
    restart: always
    container_name: nginx
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/etc/nginx/cert
      - ./conf.d:/etc/nginx/conf.d
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    networks:
      net_frontend:
        ipv4_address: 172.16.238.2
      net_backend:
        ipv4_address: 172.16.239.2



networks:
  net_frontend:
    name: net_frontend
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  net_backend:
    name: net_backend
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
