version: "3.5"
services:
  alertmanager:
    image: ${REPO_NAME}/${PROJECT}/prom/alertmanager:latest
    container_name: alertmanager
    hostname: alertmanager1
    restart: always
    attach: false
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --cluster.listen-address=0.0.0.0:9094
      - --cluster.advertise-address=$XDESK_NODE_01_IP:9094
      - --cluster.peer=$XDESK_NODE_02_IP:9094
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      # - 9093:9093
      - 9094:9094
    networks:
      frontend:

networks:
  frontend:
    external: true
  backend:
    external: true
