# 2024-11-22 13:42:22
# 测试通过
# renjiangzhou@xfusion.com

apiVersion: 1

deleteDatasources:
  - name: camptocamp-prometheus-alertmanager-datasource

datasources:
  - name: alertmanager
    type: camptocamp-prometheus-alertmanager-datasource
    access: proxy
    orgId: 1
    url: http://alertmanager:9093
    isDefault: false
    jsonData:
      tlsSkipVerify: true
    readOnly: false
