version: '3.7'

services:
  manim:
    image: hub.xfusion.com/library/manimcommunity/manim:stable
    container_name: manim
    user: "1000:1000"
    volumes:
      - ./scripts:/manim
    ports:
      - 8887:8888
    command: jupyter lab --ip=0.0.0.0
    stdin_open: true
    tty: true
    # environment:
    #   - UID='1000'
    #   - GID='1000'
