networks:
  graylog:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  mongodb1:
    image: "mongo:5.0"
    hostname: "mongodb1"
    command: ["mongod", "--bind_ip_all", "--replSet", "rs0"]
    volumes:
      - "mongodb-data-01:/data/db"
      - "./mongodb/initdb.d:/docker-entrypoint-initdb.d"
      - "./mongodb/init-replset.js:/init-replset.js"
    networks:
      graylog:
        ipv4_address: 172.20.0.2
    restart: "on-failure"

  mongodb2:
    image: "mongo:5.0"
    hostname: "mongodb2"
    command: ["mongod", "--bind_ip_all", "--replSet", "rs0"]
    volumes:
      - "mongodb-data-02:/data/db"
    networks:
      graylog:
        ipv4_address: 172.20.0.3
    restart: "on-failure"

  mongodb3:
    image: "mongo:5.0"
    hostname: "mongodb3"
    command: ["mongod", "--bind_ip_all", "--replSet", "rs0"]
    volumes:
      - "mongodb-data-03:/data/db"
    networks:
      graylog:
        ipv4_address: 172.20.0.4
    restart: "on-failure"

volumes:
  mongodb-data-01:
  mongodb-data-02:
  mongodb-data-03: