version: '3.8'

services:
  kuboard-spray:
<<<<<<< HEAD
    image: eipwork/kuboard-spray:latest-amd64
=======
    image: swr.cn-east-2.myhuaweicloud.com/kuboard/kuboard-spray:latest-amd64
>>>>>>> origin/main
    container_name: kuboard-spray
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
<<<<<<< HEAD
      - "80:80/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kuboard-spray-data:/data
=======
      - "8080:80/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/kuboard-spray-data:/data

  kuboard:
    image: swr.cn-east-2.myhuaweicloud.com/kuboard/kuboard:v3
    container_name: kuboard
    restart: unless-stopped
    ports:
      - "8081:80"
      - "10081:10081"
    environment:
      - KUBOARD_ENDPOINT=http://10.32.140.171:8080
      - KUBOARD_AGENT_SERVER_TCP_PORT=10081
    volumes:
      - ~/kuboard-data:/data

>>>>>>> origin/main
