name: AI

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  MaxKB:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull and Save Docker images
        run: |
          docker pull cr2.fit2cloud.com/1panel/maxkb
          docker save -o maxkb.tar.gz cr2.fit2cloud.com/1panel/maxkb

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maxkb
          path: maxkb.tar.gz

  onerahmet_openai-whisper-asr-webservice_latest:
    runs-on: ubuntu-latest

    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Image as File
        run: |
          docker pull onerahmet/openai-whisper-asr-webservice:latest
          docker save -o onerahmet_openai-whisper-asr-webservice_latest.tar.gz onerahmet/openai-whisper-asr-webservice:latest

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: onerahmet_openai-whisper-asr-webservice_latest
          path: onerahmet_openai-whisper-asr-webservice_latest.tar.gz

  ollama:
    runs-on: ubuntu-latest

    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Image as File
        run: |
          docker pull ollama/ollama:0.5.7
          docker save -o ollama_ollama_0.5.7.tar.gz ollama/ollama:0.5.7

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ollama_ollama_0.5.7
          path: ollama_ollama_0.5.7.tar.gz

  open-webui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Image as File
        run: |
          docker pull ghcr.io/open-webui/open-webui:main
          docker save -o open-webui_main.tar.gz ghcr.io/open-webui/open-webui:main

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: open-webui_main
          path: open-webui_main.tar.gz
