name: AI

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  onerahmet_openai-whisper-asr-webservice:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Image as File
        run: |
          docker pull onerahmet/openai-whisper-asr-webservice:latest
          docker save -o onerahmet_openai-whisper-asr-webservice_latest.tar.gz onerahmet/openai-whisper-asr-webservice:latest

          docker pull onerahmet/openai-whisper-asr-webservice:latest-gpu
          docker save -o onerahmet_openai-whisper-asr-webservice_latest-gpu.tar.gz onerahmet/openai-whisper-asr-webservice:latest-gpu

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: onerahmet_openai-whisper-asr-webservice_latest
          path: onerahmet_openai-whisper-asr-webservice_latest.tar.gz

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: onerahmet_openai-whisper-asr-webservice_latest-gpu
          path: onerahmet_openai-whisper-asr-webservice_latest-gpu.tar.gz
