name: Custom2

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # 每周日凌晨0点执行

jobs:
  docling:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull and Save Image as File
        run: |
          pip run docling
          docling-tools models download
