name: docling

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  docling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Pull and Save Docker images
        run: |
          git clone https://github.com/DS4SD/docling.git

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: ./docling
          file: ./docling/Dockerfile
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/docling:main
            ${{ secrets.DOCKER_USERNAME }}/docling:${{ github.sha }}
          push: true
