# Pull and Save Docker Images
name: Grafana

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  Grafana:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Image as File
        run: |
          docker pull grafana/grafana:latest
          docker save -o grafana_grafana_latest.tar.gz grafana/grafana:latest

          docker pull grafana/grafana:11.4.0
          docker save -o grafana_grafana_11.4.0.tar.gz grafana/grafana:11.4.0

          docker pull grafana/grafana:10.3.12
          docker save -o grafana_grafana_10.3.12.tar.gz grafana/grafana:10.3.12

          docker pull grafana/grafana:10.2.0
          docker save -o grafana_grafana_10.2.0.tar.gz grafana/grafana:10.2.0

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grafana_grafana_latest
          path: grafana_grafana_latest.tar.gz

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grafana_grafana_11.4.0
          path: grafana_grafana_11.4.0.tar.gz

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grafana_grafana_10.3.12
          path: grafana_grafana_10.3.12.tar.gz

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grafana_grafana_10.2.0
          path: grafana_grafana_10.2.0.tar.gz

  Grafana-OnCall:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Image as File
        run: |
          docker pull grafana/oncall:latest
          docker save -o grafana_oncall_latest.tar.gz grafana/oncall:latest

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grafana_oncall_latest
          path: grafana_oncall_latest.tar.gz
