name: Pull and Save Multiple Docker Images

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:

  Grafana:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Grafana Image as File  
        run: |
          docker pull grafana/grafana:latest
          docker save grafana/grafana:latest grafana-latest.tar.gz

      - name: Upload Grafana Image Artifact  
        uses: actions/upload-artifact@v4 
        with:
          name: grafana-latest
          path: grafana-latest.tar.gz

  NetBox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Grafana Image as File  
        run: |
          docker pull netboxcommunity/netbox:latest
          docker save netboxcommunity/netbox:latest netbox-latest.tar.gz

      - name: Upload Grafana Image Artifact  
        uses: actions/upload-artifact@v4 
        with:
          name: netbox-latest
          path: netbox-latest.tar.gz

  Grafana-OnCall:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Grafana OnCall Image as File  
        run: |
          docker pull grafana/oncall:latest
          docker save grafana/oncall:latest grafana-oncall-latest.tar.gz

      - name: Upload Grafana OnCall Image Artifact  
        uses: actions/upload-artifact@v4 
        with:
          name: grafana-oncall-latest
          path: grafana-oncall-latest.tar.gz