# Pull and Save Graylog Docker Images

# https://hub.docker.com/u/graylog
# https://hub.docker.com/r/opensearchproject/opensearch

name: Pull and Save Graylog Docker Images

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:

  Graylog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Graylog Image 
        run: |
          docker pull graylog/graylog:6.0
          docker save -o graylog-6.0.tar.gz graylog/graylog:6.0

      - name: Upload Graylog Image Artifact 
        uses: actions/upload-artifact@v4
        with:
          name: graylog-latest
          path: graylog-latest.tar.gz 

  OpenSearch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and save OpenSearch image
        run: |
            docker pull opensearchproject/opensearch:latest
            docker save -o opensearch-latest.tar.gz opensearchproject/opensearch:latest

      - name: Upload OpenSearch Image Artifact 
        uses: actions/upload-artifact@v4
        with:
          name: opensearch-latest
          path: opensearch-latest.tar.gz 