name: k8s-test

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  Kuboard-Spray:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Grafana Image as File
        run: |
          docker pull swr.cn-east-2.myhuaweicloud.com/kuboard/kuboard-spray:latest-amd64
          docker save -o kuboard-spray-latest-amd64.tar.gz swr.cn-east-2.myhuaweicloud.com/kuboard/kuboard-spray:latest-amd64

      - name: Upload Grafana Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kuboard-spray-latest-amd64
          path: kuboard-spray-latest-amd64.tar.gz

  Resource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Image as File
        run: |
          docker pull registry.cn-shanghai.aliyuncs.com/kuboard-spray/kuboard-spray-resource:spray-v2.21.0c_k8s-v1.26.4_v4.4-amd64
          docker save -o kuboard-spray-resource:spray-v2.21.0c_k8s-v1.26.4_v4.4-amd64.tar.gz registry.cn-shanghai.aliyuncs.com/kuboard-spray/kuboard-spray-resource:spray-v2.21.0c_k8s-v1.26.4_v4.4-amd64

      - name: Upload Grafana OnCall Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kuboard-spray-resource:spray-v2.21.0c_k8s-v1.26.4_v4.4-amd64
          path: kuboard-spray-resource:spray-v2.21.0c_k8s-v1.26.4_v4.4-amd64.tar.gz
