name: OpenJDK

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          # 这里添加你的构建命令

          # openjdk
          docker pull kong:latest
          docker save -o kong_latest.tar.gz kong:latest

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kong_latest
          path: kong_latest.tar.gz
