name: Kong

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  Kong:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          docker pull kong:latest
          docker save -o kong_latest.tar.gz kong:latest

          docker pull bitnami/kong:latest
          docker save -o bitnami_kong_latest.tar.gz bitnami/kong:latest

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kong_latest
          path: kong_latest.tar.gz

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bitnami_kong_latest
          path: bitnami_kong_latest.tar.gz