name: MaxKB

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull and Save Docker images
        run: |
          docker pull cr2.fit2cloud.com/1panel/maxkb
          docker save -o maxkb.tar.gz cr2.fit2cloud.com/1panel/maxkb

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maxkb
          path: maxkb.tar.gz