# Pull and Save NetBox Docker Images
name: NetBox Docker Images

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  NetBox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Grafana Image as File
        run: |
          docker pull netboxcommunity/netbox:latest
          docker save -o netbox-latest.tar.gz netboxcommunity/netbox:latest

      - name: Upload Grafana Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: netbox-latest
          path: netbox-latest.tar.gz
