name: NetworkOps

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  librespeed:
    # https://github.com/librespeed/speedtest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          docker pull ghcr.io/librespeed/speedtest:latest
          docker save -o librespeed_latest.tar.gz ghcr.io/librespeed/speedtest:latest

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: librespeed_latest
          path: librespeed_latest.tar.gz

  librespeed-linuxserver:
    # https://github.com/linuxserver/docker-librespeed
    # https://github.com/librespeed/speedtest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          docker pull linuxserver/librespeed:latest
          docker save -o linuxserver_librespeed_latest.tar.gz linuxserver/librespeed:latest

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linuxserver_librespeed_latest
          path: linuxserver_librespeed_latest.tar.gz

  NetBox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Grafana Image as File
        run: |
          docker pull netboxcommunity/netbox:latest
          docker save -o netbox-latest.tar.gz netboxcommunity/netbox:latest

      - name: Upload Grafana Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: netbox-latest
          path: netbox-latest.tar.gz

  Nautobot-Custom-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Nautobot image with plugins
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packaging/docker/custom/Dockerfile.nautobot
          build-args: |
            NAUTOBOT_VERSION=latest
          tags: nautobot-custom:latest
          load: true

      - name: Save Nautobot Docker image as file
        run: |
          docker save -o nautobot-custom_latest.tar.gz nautobot-custom:latest

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nautobot-custom_latest
          path: nautobot-custom_latest.tar.gz

  Nautobot-Custom-stable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Nautobot image with plugins
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packaging/docker/custom/Dockerfile.nautobot
          build-args: |
            NAUTOBOT_VERSION=stable
          tags: nautobot-custom:stable
          load: true

      - name: Save Nautobot Docker image as file
        run: |
          docker save -o nautobot-custom_stable.tar.gz nautobot-custom:stable

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nautobot-custom_stable
          path: nautobot-custom_stable.tar.gz

  Nautobot-Custom-2_4:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image with plugins
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packaging/docker/custom/Dockerfile.nautobot
          build-args: |
            NAUTOBOT_VERSION=2.4
          tags: nautobot-custom:2.4
          load: true

      - name: Save Docker image as file
        run: |
          docker save -o nautobot-custom_2.4.tar.gz nautobot-custom:2.4

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nautobot-custom_2.4
          path: nautobot-custom_2.4.tar.gz
