name: NetworkOps

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  librespeed:
    # https://github.com/librespeed/speedtest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          docker pull ghcr.io/librespeed/speedtest:latest
          docker save -o librespeed_latest.tar.gz ghcr.io/librespeed/speedtest:latest

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: librespeed_latest
          path: librespeed_latest.tar.gz

  librespeed-linuxserver:
    # https://github.com/linuxserver/docker-librespeed
    # https://github.com/librespeed/speedtest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          docker pull linuxserver/librespeed:latest
          docker save -o linuxserver_librespeed_latest.tar.gz linuxserver/librespeed:latest

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linuxserver_librespeed_latest
          path: linuxserver_librespeed_latest.tar.gz

  NetBox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Grafana Image as File
        run: |
          docker pull netboxcommunity/netbox:latest
          docker save -o netbox-latest.tar.gz netboxcommunity/netbox:latest

      - name: Upload Grafana Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: netbox-latest
          path: netbox-latest.tar.gz

  Nautobot-Plugins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Nautobot image with plugins
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packaging/docker/custom/Dockerfile.nautobot
          build-args: |
            NAUTOBOT_VERSION=latest
          tags: ${{ secrets.DOCKER_USERNAME }}/nautobot-plugins:latest
          load: true
          push: true

      - name: Build and push Nautobot image with plugins
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packaging/docker/custom/Dockerfile.nautobot
          build-args: |
            NAUTOBOT_VERSION=stable
          tags: ${{ secrets.DOCKER_USERNAME }}/nautobot-plugins:stable
          load: true
          push: true

      - name: Build and push image with plugins
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packaging/docker/custom/Dockerfile.nautobot
          build-args: |
            NAUTOBOT_VERSION=2.4
          tags: ${{ secrets.DOCKER_USERNAME }}/nautobot-plugins:2.4
          load: true
          push: true
