name: NetworkOps

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  librespeed:
    # https://github.com/librespeed/speedtest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          docker pull ghcr.io/librespeed/speedtest:latest
          docker save -o librespeed_latest.tar.gz docker pull ghcr.io/librespeed/speedtest:latest

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: librespeed_latest
          path: librespeed_latest.tar.gz

  librespeed-linuxserver:
    # https://github.com/linuxserver/docker-librespeed
    # https://github.com/librespeed/speedtest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          docker pull linuxserver/librespeed:latest
          docker save -o linuxserver_librespeed_latest.tar.gz inuxserver/librespeed:latest

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linuxserver_librespeed_latest
          path: linuxserver_librespeed_latest.tar.gz

  NetBox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and Save Grafana Image as File
        run: |
          docker pull netboxcommunity/netbox:latest
          docker save -o netbox-latest.tar.gz netboxcommunity/netbox:latest

      - name: Upload Grafana Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: netbox-latest
          path: netbox-latest.tar.gz

  Nautobot-Custom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Nautobot image with plugins
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packaging/docker/custom/Dockerfile.nautobot
          tags: nautobot:latest
          load: true

      - name: Save Nautobot Docker image as file
        run: |
          docker save -o nautobot-latest.tar.gz nautobot:latest

      - name: Upload Nautobot Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nautobot-latest
          path: nautobot-latest.tar.gz
