name: Build and Release

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          # 这里添加你的构建命令
          mkdir -p output

          # Nginx
          docker pull nginx:stable
          docker save -o output/nginx-stable.tar.gz nginx:stable

          # PostgreSQL
          docker pull postgres:latest
          docker save -o output/postgres-latest.tar.gz postgres:latest

          # postgresql-repmgr-latest
          docker pull bitnami/postgresql-repmgr:latest
          docker save -o output/postgresql-repmgr-latest.tar.gz bitnami/postgresql-repmgr:latest

          # pgpool-latest
          docker pull bitnami/pgpool:latest
          docker save -o output/pgpool-latest.tar.gz bitnami/pgpool:latest

          # pgadmin4-latest
          docker pull dpage/pgadmin4:latest
          docker save -o output/pgadmin4-latest.tar.gz dpage/pgadmin4:latest

          # MySQL
          docker pull mysql:8.0 
          docker save -o output/mysql-8.0.tar.gz mysql:8.0

          # MongoDB
          docker pull mongo:5.0
          docker save -o output/mongo-5.0.tar.gz mongo:5.0

          # Redis
          docker pull redis:7-alpine
          docker save -o output/redis-7-alpine.tar.gz redis:7-alpine

          # Graylog
          docker pull graylog/graylog:6.1
          docker save -o output/graylog-6.1.tar.gz graylog/graylog:6.1

          # Graylog-OpenSearch
          docker pull opensearchproject/opensearch:2.15.0
          docker save -o output/opensearch-2.15.0.tar.gz opensearchproject/opensearch:2.15.0

          # Graylog-DataNode
          docker pull graylog/graylog-datanode:6.1
          docker save -o output/graylog-datanode-6.1.tar.gz graylog/graylog-datanode:6.1

          # Prometheus
          docker pull prom/prometheus:latest
          docker save -o output/prom-prometheus-latest.tar.gz prom/prometheus:latest

          # Prometheus-ALertmanager
          docker pull prom/alertmanager:latest
          docker save -o output/prom-alertmanager-latest.tar.gz prom/alertmanager:latest

          # Zabbix-Server
          docker pull zabbix/zabbix-server-pgsql:alpine-7.0-latest
          docker save -o output/zabbix-server-pgsql-alpine-7.0-latest.tar.gz zabbix/zabbix-server-pgsql:alpine-7.0-latest
                     
          # Zabbix-Proxy
          docker pull zabbix/zabbix-proxy-mysql:alpine-7.0-latest
          docker save -o output/zabbix-proxy-mysql-alpine-7.0-latest.tar.gz zabbix/zabbix-proxy-mysql:alpine-7.0-latest

          # Zabbix-Web
          docker pull zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
          docker save -o output/zabbix-web-nginx-pgsql-alpine-7.0-latest.tar.gz zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest

      - name: Create Release
        id: create_release
        run: |
          gh release create "$tag" \
            output/* \
            --title="${tag#v}" \
            --notes "update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
