name: Speedtest

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  librespeed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          docker pull linuxserver/librespeed:latest
          docker save -o linuxserver_librespeed_latest.tar.gz inuxserver/librespeed:latest

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linuxserver_librespeed_latest
          path: linuxserver_librespeed_latest.tar.gz
