name: test

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:

  NetBox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: get harbor
        run: |
          wget https://github.com/goharbor/harbor/releases/download/v2.11.1/harbor-offline-installer-v2.11.1.tgz

          docker pull bitnami/postgresql-repmgr:latest
          docker save bitnami/postgresql-repmgr:latest > postgresql-repmgr-latest.tar.gz

          docker pull bitnami/pgpool:latest
          docker save bitnami/pgpool:latest > pgpool-latest.tar.gz

          docker pull dpage/pgadmin4:latest
          docker save dpage/pgadmin4:latest > pgadmin4-latest.tar.gz

          docker pull frooodle/s-pdf:latest
          docker save frooodle/s-pdf:latest > frooodle-s-pdf:latest.tar.gz
          
      - name: Upload Grafana Image Artifact  
        uses: actions/upload-artifact@v4 
        with:
          name: harbor-offline-installer
          path: harbor-offline-installer-v2.11.1.tgz

      - name: Upload Grafana Image Artifact  
        uses: actions/upload-artifact@v4 
        with:
          name: postgresql-repmgr-latest
          path: postgresql-repmgr-latest.tar.gz

      - name: Upload Grafana Image Artifact  
        uses: actions/upload-artifact@v4 
        with:
          name: pgpool-latest
          path: pgpool-latest.tar.gz

      - name: Upload Grafana Image Artifact  
        uses: actions/upload-artifact@v4 
        with:
          name: pgadmin4-latest
          path: pgadmin4-latest.tar.gz
