name: NetworkOps

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  Nautobot-Plugins:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nautobot_version: [latest, stable, stable-py3.12, 2.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Nautobot image with plugins
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packaging/docker/custom/Dockerfile.nautobot
          build-args: |
            NAUTOBOT_VERSION=${{ matrix.nautobot_version }}
          tags: ${{ secrets.DOCKER_USERNAME }}/nautobot-plugins:${{ matrix.nautobot_version }}
          load: true
          push: true
