name: Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # 每周日凌晨0点执行

jobs:
  Nautobot-Plugins:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5 # 限制同时运行的任务数量
      matrix:
        nautobot_version: [
            latest,
            latest-py3.12,
            latest-py3.11,
            latest-py3.10,
            latest-py3.9,
            latest-py3.8,
            stable,
            stable-py3.12,
            stable-py3.11,
            stable-py3.10,
            stable-py3.9,
            stable-py3.8,
            # stable-py3.7,
            # stable-py3.6,
            2.4,
            2.4-py3.12,
            2.4-py3.11,
            2.4-py3.10,
            2.4-py3.9,
          ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.version }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Nautobot image with plugins
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packaging/docker/custom/Dockerfile.nautobot
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            NAUTOBOT_VERSION=${{ matrix.nautobot_version }}
          tags: ${{ secrets.DOCKER_USERNAME }}/nautobot-plugins:${{ matrix.nautobot_version }}
          load: true
          push: true

  Grafana-Plugins:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5 # 限制同时运行的任务数量
      matrix:
        nautobot_version:
          [
            latest,
            11.5.1,
            11.5.0,
            11.4.1,
            11.4.0,
            11.3.3,
            11.3.2,
            11.3.1,
            11.3.0+security-01,
            11.3.0,
            11.2.6,
            11.2.5,
            11.2.4,
            11.2.3+security-01,
            11.2.3,
            11.2.2+security-01,
            11.2.2,
            11.2.1+security-01,
            11.2.1,
            11.2.0,
            11.1.11,
            11.1.10,
            11.1.9,
            11.1.8,
            11.1.7+security-01,
            11.1.7,
            11.1.6+security-01,
            11.1.6,
            11.1.5,
            11.1.4,
            11.1.3,
            11.1.2,
            11.1.1,
            11.1.0,
            11.0.10,
            11.0.9,
            11.0.8,
            11.0.7,
            11.0.6+security-01,
            11.0.6,
            11.0.5+security-01,
            11.0.5,
            11.0.4,
            11.0.3,
            11.0.2,
            11.0.1,
            11.0.0,
            11.0.0-preview,
            10.4.15,
            10.4.14,
            10.4.13,
            10.4.12,
            10.4.11,
            10.4.10,
            10.4.9,
            10.4.8,
            10.4.7,
            10.4.6,
            10.4.5,
            10.4.4,
            10.4.3,
            10.4.2,
            10.4.1,
            10.4.0,
            10.3.12,
            10.3.11,
            10.3.10,
            10.3.9,
            10.3.7,
            10.3.6,
            10.3.5,
            10.3.4,
            10.3.3,
            10.3.1,
            10.3.0,
            10.2.9,
            10.2.8,
            10.2.7,
            10.2.6,
            10.2.5,
            10.2.4,
            10.2.3,
            10.2.2,
            10.2.1,
            10.2.0,
            10.1.10,
            10.1.9,
            10.1.8,
            10.1.7,
            10.1.6,
            10.1.5,
            10.1.4,
            10.1.2,
            10.1.1,
            10.1.0,
            10.0.13,
            10.0.12,
            10.0.11,
            10.0.10,
            10.0.9,
            10.0.8,
            10.0.6,
            10.0.5,
            10.0.4,
            10.0.3,
            10.0.2,
            10.0.1,
            10.0.0,
            10.0.0-preview,
            9.5.21,
            9.5.20,
            9.5.19,
            9.5.18,
            9.5.17,
            9.5.16,
            9.5.15,
            9.5.14,
            9.5.13,
            9.5.12,
            9.5.10,
            9.5.9,
            9.5.8,
            9.5.7,
            9.5.6,
            9.5.5,
            9.5.3,
            9.5.2,
            9.5.1,
            9.5.0,
            9.4.17,
            9.4.15,
            9.4.14,
            9.4.13,
            9.4.12,
            9.4.10,
            9.4.9,
            9.4.7,
            9.4.3,
            9.4.2,
            9.4.1,
            9.4.0,
            9.4.0-beta1,
            9.3.16,
            9.3.15,
            9.3.14,
            9.3.13,
            9.3.11,
            9.3.8,
            9.3.6,
            9.3.4,
            9.3.2,
            9.3.1,
            9.3.0,
            9.3.0-beta1,
            9.2.20,
            9.2.19,
            9.2.18,
            9.2.17,
            9.2.15,
            9.2.13,
            9.2.10,
            9.2.8,
            9.2.7,
            9.2.6,
            9.2.5,
            9.2.4,
            9.2.3,
            9.2.2,
            9.2.1,
            9.2.0,
            9.2.0-beta1,
            9.1.8,
            9.1.7,
            9.1.6,
            9.1.5,
            9.1.4,
            9.1.3,
            9.1.2,
            9.1.1,
            9.1.0,
            9.1.0-beta1,
            9.0.9,
            9.0.8,
            9.0.7,
            9.0.6,
            9.0.5,
            9.0.4,
            9.0.3,
            9.0.2,
            9.0.1,
            9.0.0,
            9.0.0-beta3,
            9.0.0-beta2,
            9.0.0-beta1,
            8.5.27,
            8.5.26,
            8.5.25,
            8.5.24,
            8.5.22,
            8.5.21,
            8.5.20,
            8.5.16,
            8.5.15,
            8.5.14,
            8.5.13,
            8.5.11,
            8.5.10,
            8.5.9,
            8.5.6,
            8.5.5,
            8.5.4,
            8.5.3,
            8.5.2,
            8.5.1,
            8.5.0,
            8.5.0-beta1,
            8.4.11,
            8.4.10,
            8.4.7,
            8.4.6,
            8.4.5,
            8.4.4,
            8.4.3,
            8.4.2,
            8.4.1,
            8.4.0,
            8.4.0-beta1,
            8.3.11,
            8.3.10,
            8.3.7,
            8.3.6,
            8.3.5,
            8.3.4,
            8.3.3,
            8.3.2,
            8.3.1,
            8.3.0,
            # 8.3.0-beta2,
            # 8.3.0-beta1,
            8.2.7,
            8.2.6,
            8.2.5,
            8.2.4,
            8.2.3,
            8.2.2,
            8.2.1,
            8.2.0,
            # 8.2.0-beta2,
            # 8.2.0-beta1,
            8.1.8,
            8.1.7,
            8.1.6,
            8.1.5,
            8.1.4,
            8.1.3,
            8.1.2,
            8.1.1,
            8.1.0,
            # 8.1.0-beta3,
            # 8.1.0-beta2,
            # 8.1.0-beta1,
            8.0.7,
            8.0.6,
            8.0.5,
            8.0.4,
            8.0.3,
            8.0.2,
            8.0.1,
            8.0.0,
            # 8.0.0-beta3,
            # 8.0.0-beta2,
            # 8.0.0-beta1,
            7.5.17,
            7.5.16,
            7.5.15,
            7.5.13,
            7.5.12,
            7.5.11,
            7.5.10,
            7.5.9,
            7.5.8,
            7.5.7,
            7.5.6,
            7.5.5,
            7.5.4,
            7.5.3,
            7.5.2,
            7.5.1,
            # 7.5.0-beta2,
            # 7.5.0-beta1,
            7.4.5,
            7.4.3,
            7.4.2,
            7.4.1,
            7.4.0,
            # 7.4.0-beta1,
            7.3.10,
            7.3.7,
            7.3.6,
            7.3.5,
            7.3.4,
            7.3.3,
            7.3.2,
            7.3.1,
            7.3.0,
            # 7.3.0-beta2,
            # 7.3.0-beta1,
            7.2.2,
            7.2.1,
            7.2.0,
            # 7.2.0-beta2,
            # 7.2.0-beta1,
            7.1.5,
            7.1.4,
            7.1.3,
            7.1.2,
            7.1.1,
            7.1.0,
            # 7.1.0-beta3,
            # 7.1.0-beta2,
            # 7.1.0-beta1,
            7.0.6,
            7.0.5,
            7.0.4,
            7.0.3,
            7.0.2,
            7.0.1,
            7.0.0,
            # 7.0.0-beta3,
            # 7.0.0-beta2,
            # 7.0.0-beta1,
            6.7.6,
            6.7.5,
            6.7.4,
            6.7.3,
            6.7.2,
            6.7.1,
            6.7.0,
            # 6.7.0-beta1,
            6.6.2,
            6.6.1,
            6.6.0,
            # 6.6.0-beta1,
            6.5.3,
            6.5.2,
            6.5.1,
            6.5.0,
            # 6.5.0-beta1,
            6.4.5,
            6.4.4,
            6.4.3,
            6.4.2,
            6.4.1,
            6.4.0,
            # 6.4.0-beta2,
            # 6.4.0-beta1,
            6.3.7,
            6.3.6,
            6.3.5,
            6.3.4,
            6.3.3,
            6.3.2,
            6.3.1,
            6.3.0,
            # 6.3.0-beta4,
            # 6.3.0-beta3,
            # 6.3.0-beta2,
            # 6.3.0-beta1,
            6.2.5,
            6.2.4,
            6.2.3,
            6.2.2,
            6.2.1,
            6.2.0,
            # 6.2.0-beta2,
            # 6.2.0-beta1,
            6.1.6,
            6.1.5,
            6.1.4,
            6.1.3,
            6.1.2,
            6.1.1,
            6.1.0,
            # 6.1.0-beta1,
            6.0.2,
            6.0.1,
            6.0.0,
            # 6.0.0-beta3,
            # 6.0.0-beta2,
            # 6.0.0-beta1,
            5.4.5,
            5.4.4,
            5.4.3,
            5.4.2,
            5.4.1,
            5.4.0,
            # 5.4.0-beta1
          ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.version }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push with plugins
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packaging/docker/custom/Dockerfile.grafana
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            GRAFANA_VERSION=${{ matrix.nautobot_version }}
            GF_INSTALL_PLUGINS=grafana-clock-panel,alexanderzobnin-zabbix-app,camptocamp-prometheus-alertmanager-datasource,grafana-opensearch-datasource,marcusolsson-csv-datasource,volkovlabs-grapi-datasource,marcusolsson-json-datasource,yesoreyeram-infinity-datasource
          tags: ${{ secrets.DOCKER_USERNAME }}/grafana-plugins:${{ matrix.nautobot_version }}
          load: true
          push: true
