name: test

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  NetBox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: get harbor
        run: |



          docker pull frooodle/s-pdf:latest
          docker save frooodle/s-pdf:latest > frooodle-s-pdf-latest.tar.gz

      - name: Upload Grafana Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: harbor-offline-installer
          path: harbor-offline-installer-v2.11.1.tgz

      - name: Upload Grafana Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: postgresql-repmgr-latest
          path: postgresql-repmgr-latest.tar.gz

      - name: Upload Grafana Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pgpool-latest
          path: pgpool-latest.tar.gz

      - name: Upload Grafana Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pgadmin4-latest
          path: pgadmin4-latest.tar.gz

      - name: Upload Grafana Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frooodle-s-pdf-latest
          path: frooodle-s-pdf-latest.tar.gz
