name: Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # 每周日凌晨0点执行

jobs:
  Nautobot-Plugins:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5 # 限制同时运行的任务数量
      matrix:
        nautobot_version:
          [
            latest,
            latest-py3.12,
            latest-py3.11,
            latest-py3.10,
            latest-py3.9,
            latest-py3.8,
            stable,
            stable-py3.12,
            stable-py3.11,
            stable-py3.10,
            stable-py3.9,
            stable-py3.8,
            stable-py3.7,
            stable-py3.6,
            2.4,
            2.4-py3.12,
            2.4-py3.11,
            2.4-py3.10,
            2.4-py3.9,
          ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.version }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Nautobot image with plugins
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packaging/docker/custom/Dockerfile.nautobot
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            NAUTOBOT_VERSION=${{ matrix.nautobot_version }}
          tags: ${{ secrets.DOCKER_USERNAME }}/nautobot-plugins:${{ matrix.nautobot_version }}
          load: true
          push: true

  Grafana-Plugins:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5 # 限制同时运行的任务数量
      matrix:
        nautobot_version: [latest, 10.2.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.version }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push with plugins
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packaging/docker/custom/Dockerfile.grafana
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            GRAFANA_VERSION=${{ matrix.nautobot_version }}
            GF_INSTALL_PLUGINS=grafana-clock-panel,alexanderzobnin-zabbix-app,camptocamp-prometheus-alertmanager-datasource,grafana-opensearch-datasource,marcusolsson-csv-datasource,volkovlabs-grapi-datasource,marcusolsson-json-datasource,yesoreyeram-infinity-datasource
          tags: ${{ secrets.DOCKER_USERNAME }}/grafana-plugins:${{ matrix.nautobot_version }}
          load: true
