name: OpenJDK

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          docker pull portainer/portainer:latest
          docker save -o portainer_portainer_latest.tar.gz portainer/portainer:latest

          docker pull ccr.ccs.tencentyun.com/chenyinxin/xlink-platform:2409251213

          
          docker pull ccr.ccs.tencentyun.com/chenyinxin/xlink-portal:latest

          docker pull ccr.ccs.tencentyun.com/chenyinxin/eipservice:latest


      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: portainer_portainer_latest
          path: portainer_portainer_latest.tar.gz
