name: Pull and Save Zabbix Docker Images

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  Zabbix:
    # docker pull zabbix/zabbix-server-pgsql:latest
    # docker pull zabbix/zabbix-proxy-mysql:latest
    # docker pull zabbix/zabbix-web-nginx-pgsql:latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and save Zabbix Server PostgreSQL image
        run: |
          docker pull zabbix/zabbix-server-pgsql:latest
          docker save zabbix/zabbix-server-pgsql:latest zabbix-server-pgsql-latest.tar.gz

      - name: Upload Zabbix Server PostgreSQL image artifact
        uses: actions/upload-artifact@v4
        with:
          name: zabbix-server-pgsql-latest
          path: zabbix-server-pgsql-latest.tar.gz

      - name: Pull and save Zabbix Proxy MySQL image
        run: |
          docker pull zabbix/zabbix-proxy-mysql:latest
          docker save zabbix/zabbix-proxy-mysql:latest zabbix-proxy-mysql-latest.tar.gz

      - name: Upload Zabbix Proxy MySQL image artifact
        uses: actions/upload-artifact@v4
        with:
          name: zabbix-proxy-mysql-latest
          path: zabbix-proxy-mysql-latest.tar.gz

      - name: Pull and save Zabbix Web Nginx PostgreSQL image
        run: |
          docker pull zabbix/zabbix-web-nginx-pgsql:latest
          docker save zabbix/zabbix-web-nginx-pgsql:latest zabbix-web-nginx-pgsql-latest.tar.gz

      - name: Upload Zabbix Web Nginx PostgreSQL image artifact
        uses: actions/upload-artifact@v4
        with:
          name: zabbix-web-nginx-pgsql-latest
          path: zabbix-web-nginx-pgsql-latest.tar.gz
